import { NextRequest, NextResponse } from "next/server";
import jwt from "jsonwebtoken";
import { v4 as uuidv4 } from "uuid";

// Environment variables required:
// GOOGLE_ISSUER_ID: Your Google Pay Issuer ID
// GOOGLE_CLIENT_EMAIL: Service Account Email
// GOOGLE_PRIVATE_KEY: Service Account Private Key (PEM format)

export async function POST(req: NextRequest) {
  try {
    const { barcode, format, backgroundColor, label } = await req.json();

    const issuerId = process.env.GOOGLE_ISSUER_ID;
    const clientEmail = process.env.GOOGLE_CLIENT_EMAIL;
    // Handle private key newlines from env vars
    const privateKey = process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n');

    if (!issuerId || !clientEmail || !privateKey) {
      console.error("Missing Google Wallet environment variables");
      return NextResponse.json({
        message: "Server configuration error: Missing Google Wallet credentials."
      }, { status: 500 });
    }

    if (!barcode) {
      return NextResponse.json({ message: "Barcode is required" }, { status: 400 });
    }

    // Map scanner formats to Google Wallet barcode types
    // https://developers.google.com/wallet/generic/rest/v1/Barcode
    let googleBarcodeType = "qrCode";
    let googleBarcodeValue = barcode;
    
    // Normalize format
    const fmt = (format || "").toUpperCase();
    if (fmt.includes("QR")) googleBarcodeType = "qrCode";
    else if (fmt.includes("PDF_417")) googleBarcodeType = "pdf417";
    else if (fmt.includes("AZTEC")) googleBarcodeType = "aztec";
    else if (fmt.includes("CODE_128")) googleBarcodeType = "code128";
    else if (fmt.includes("CODE_39")) googleBarcodeType = "code39";
    else if (fmt.includes("EAN_13")) googleBarcodeType = "ean13";
    else if (fmt.includes("EAN_8")) googleBarcodeType = "ean8";
    else if (fmt.includes("UPC_A")) googleBarcodeType = "upcA";
    else if (fmt.includes("UPC_E")) googleBarcodeType = "upcE";
    else if (fmt.includes("CODABAR")) googleBarcodeType = "codabar";
    else if (fmt.includes("DATA_MATRIX")) googleBarcodeType = "dataMatrix";
    else {
        // Fallback or default
        googleBarcodeType = "code128";
    }

    // Define the Pass Class and Object
    // For a simple prototype, we use a Generic Class concept but define it inline if possible.
    // However, Google Wallet usually requires the Class to be defined via API or in the JWT.
    // We will assume a "Loyalty" style pass for cards.
    
    const classId = `${issuerId}.generic_card_v1`;
    const objectId = `${issuerId}.${uuidv4()}`;

    // Payload for the JWT
    // This uses the "skinny JWT" approach where we define the object inside the token
    // Note: The Class must typically exist in your Google Pay Merchant Center, 
    // BUT we can try to define it in the payload if the API allows, or simpler:
    // We assume the user has created at least one class or we try to use a generic structure.
    // actually, for "Save to Android Pay" links, passing the full Class definition in the JWT 
    // is supported for testing, but mostly you reference a Class ID.
    // To make this "just work" for a demo, we often need a valid Class ID.
    // Since we can't create a class without API calls, we will assume the user 
    // provides a valid GOOGLE_ISSUER_ID and we'll construct a standard class ID convention.
    // IF the class doesn't exist, this link might fail. 
    // A robust app would check/create the class first.
    
    // We will construct a payload that attempts to define both Class and Object.
    
    const claims = {
      iss: clientEmail,
      aud: "google",
      origins: ["https://barcode2wallet.com"],
      typ: "savetowallet",
      payload: {
        loyaltyObjects: [{
          id: objectId,
          classId: classId,
          state: "active",
          accountId: barcode,
          barcode: {
            type: googleBarcodeType,
            value: googleBarcodeValue,
            alternateText: barcode
          },
          hexBackgroundColor: backgroundColor || "#60a389",
          heroImage: {
             sourceUri: {
                uri: "https://barcode2wallet.com/og-image.png"
             }
          },
          textModulesData: [
            {
              header: "Label",
              body: label || "My Card",
            },
            {
               header: "Generated by",
               body: "Barcode to Wallet"
            }
          ]
        }]
      }
    };

    // If we want to define the class in the same payload (so it auto-creates if missing):
    // Note: This often requires the class to be in the `loyaltyClasses` array.
    // We'll add it to be safe.
    (claims.payload as any).loyaltyClasses = [{
      id: classId,
      issuerName: "Barcode to Wallet",
      programName: "Digital Wallet Pass",
      programLogo: {
        sourceUri: {
          uri: "https://barcode2wallet.com/icon-192.png" // Must be a publicly accessible URL
        }
      },
      reviewStatus: "underReview", // or "approved" if you have gone through process
      hexBackgroundColor: backgroundColor || "#60a389",
    }];

    const token = jwt.sign(claims, privateKey, { algorithm: "RS256" });
    const saveUrl = `https://pay.google.com/gp/v/save/${token}`;

    return NextResponse.json({ saveUrl });
    
  } catch (error: any) {
    console.error("Google Wallet Error:", error);
    return NextResponse.json({ message: error.message || "Internal Server Error" }, { status: 500 });
  }
}